apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
- reversedns.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: 60a174811e1355f742ad32d42bd52ff6ee96fa7d
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: 60a174811e1355f742ad32d42bd52ff6ee96fa7d
- name: charlesdburton/scandalorian-reversedns-engine:latest
  newName: charlesdburton/scandalorian-reversedns-engine
  newTag: 60a174811e1355f742ad32d42bd52ff6ee96fa7d
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: 60a174811e1355f742ad32d42bd52ff6ee96fa7d
