apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
- reversedns.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: dc287e549732c7460c70d2187fdad99f644ae428
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: dc287e549732c7460c70d2187fdad99f644ae428
- name: charlesdburton/scandalorian-reversedns-engine:latest
  newName: charlesdburton/scandalorian-reversedns-engine
  newTag: dc287e549732c7460c70d2187fdad99f644ae428
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: dc287e549732c7460c70d2187fdad99f644ae428
