apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
- reversedns.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: 5c9620f0dd518bbe1ea3ec4c3ea08e1b883e5c2d
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: 5c9620f0dd518bbe1ea3ec4c3ea08e1b883e5c2d
- name: charlesdburton/scandalorian-reversedns-engine:latest
  newName: charlesdburton/scandalorian-reversedns-engine
  newTag: 5c9620f0dd518bbe1ea3ec4c3ea08e1b883e5c2d
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: 5c9620f0dd518bbe1ea3ec4c3ea08e1b883e5c2d
