apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: 297b966447f21194e8b5b85d9cd63c04f7354bc3
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: 297b966447f21194e8b5b85d9cd63c04f7354bc3
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: 297b966447f21194e8b5b85d9cd63c04f7354bc3
