apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
- reversedns.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: 7520b76c69af7af5ebbbf0eca91dbb90d1362ec3
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: 7520b76c69af7af5ebbbf0eca91dbb90d1362ec3
- name: charlesdburton/scandalorian-reversedns-engine:latest
  newName: charlesdburton/scandalorian-reversedns-engine
  newTag: 7520b76c69af7af5ebbbf0eca91dbb90d1362ec3
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: 7520b76c69af7af5ebbbf0eca91dbb90d1362ec3
