apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
- reversedns.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: 1db9f403b2f708d4e6f80025ef76b77dc4883e58
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: 1db9f403b2f708d4e6f80025ef76b77dc4883e58
- name: charlesdburton/scandalorian-reversedns:latest
  newName: charlesdburton/scandalorian-reversedns
  newTag: c9ca90172add4e0003d6352ab7fc13abae0d41aa
<<<<<<< HEAD
- name: charlesdburton/scandalorian-reversedns-engine:latest
  newName: charlesdburton/scandalorian-reversedns-engine
  newTag: db830adf81ee85e45ef57ab8b265ecd661ca9240
=======
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: 1db9f403b2f708d4e6f80025ef76b77dc4883e58
>>>>>>> 6fd69870d44a88486de6fb28cd599862ef15d1f8
