apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
- reversedns.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: 7f9ebcb75985ce27ad69a76558c396584c95679a
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: 7f9ebcb75985ce27ad69a76558c396584c95679a
- name: charlesdburton/scandalorian-reversedns-engine:latest
  newName: charlesdburton/scandalorian-reversedns-engine
  newTag: 7f9ebcb75985ce27ad69a76558c396584c95679a
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: 7f9ebcb75985ce27ad69a76558c396584c95679a
