apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: 8fd8a65625456e92d97d9d605cc0f53b9dc2233a
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: 8fd8a65625456e92d97d9d605cc0f53b9dc2233a
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: 8fd8a65625456e92d97d9d605cc0f53b9dc2233a
