apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
- reversedns.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: 5501ed8a694529b23d51f19f301a34407781c45d
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: 5501ed8a694529b23d51f19f301a34407781c45d
- name: charlesdburton/scandalorian-reversedns-engine:latest
  newName: charlesdburton/scandalorian-reversedns-engine
  newTag: 5501ed8a694529b23d51f19f301a34407781c45d
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: 5501ed8a694529b23d51f19f301a34407781c45d
