apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingest.yaml
- discovery.yaml
- scan.yaml
images:
- name: charlesdburton/scandalorian-discovery-engine:latest
  newName: charlesdburton/scandalorian-discovery-engine
  newTag: eaf4253d13039b04f0d3325a01942bed7dbd226c
- name: charlesdburton/scandalorian-ingest:latest
  newName: charlesdburton/scandalorian-ingest
  newTag: eaf4253d13039b04f0d3325a01942bed7dbd226c
- name: charlesdburton/scandalorian-scan-engine:latest
  newName: charlesdburton/scandalorian-scan-engine
  newTag: eaf4253d13039b04f0d3325a01942bed7dbd226c
