[package]
name = "collector"
version = "0.1.0"
authors = ["Charles Burton <charles.d.burton@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nats = "0.9.7"