on: [push]

jobs:
  actions_job:
    runs-on: ubuntu-18.04
    name: A job to build multi architecture actions
    steps:
    - name: Build on arm64
      uses: ./ingest/action.yml
      with:
        architecture: arm64
        distribution: ubuntu18.04
        run: |
          apt update
          apt install -y libpcap-dev