name: Kanscan Build

on:
  push:
    branches:
      - master
jobs:
  #ingest-build-base:
  #  runs-on: ubuntu-latest
  #  name: Build the ingest application
  #  steps:
  #    - uses: actions/checkout@v1
  #    - name: Docker Login
  #      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
  #   - name: Build Base
  #      working-directory: ingest
  #      run: docker build -t ingest:base --target build --file=./Dockerfile .
  ingest-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of ingest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: ingest
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/ingest-arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/ingest-arm:latest
  ingest-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of ingest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: ingest
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/ingest-arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/ingest-arm64:latest
  ingest-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of ingest
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: ingest
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/ingest-amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/ingest-amd64:latest
  ingest-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["ingest-build-arm", "ingest-build-arm64", "ingest-build-amd64"]
    steps:
      - uses: actions/checkout@v1
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: echo "building manifest"
