name: Scandalorian Build

on:
  push:
    branches:
      - master
    paths-ignore:
      - "argocd/**"
jobs:
  ingest-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of ingest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: ingest
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-ingest:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-ingest:arm
  ingest-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of ingest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: ingest
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-ingest:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-ingest:arm64
  ingest-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of ingest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: ingest
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-ingest:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-ingest:amd64
  ingest-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push
    needs: ["ingest-build-arm", "ingest-build-arm64", "ingest-build-amd64"]
    steps:
      - uses: actions/checkout@v2
          
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/scandalorian-ingest:${{ github.sha }} \
          charlesdburton/scandalorian-ingest:amd64 \
          charlesdburton/scandalorian-ingest:arm \
          charlesdburton/scandalorian-ingest:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/scandalorian-ingest:${{ github.sha }} charlesdburton/scandalorian-ingest:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/scandalorian-ingest:${{ github.sha }} charlesdburton/scandalorian-ingest:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/scandalorian-ingest:${{ github.sha }} charlesdburton/scandalorian-ingest:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/scandalorian-ingest:${{ github.sha }}
        
  scan-engine-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of scan-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: scan-engine
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-scan-engine:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-scan-engine:arm
  scan-engine-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of scan-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: scan-engine
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-scan-engine:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-scan-engine:arm64
  scan-engine-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of scan-engine
    steps:
      - uses: actions/checkout@v2
          
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: scan-engine
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-scan-engine:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-scan-engine:amd64
  scan-engine-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push scan-engine
    needs: ["scan-engine-build-arm", "scan-engine-build-arm64", "scan-engine-build-amd64"]
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/scandalorian-scan-engine:${{ github.sha }} \
          charlesdburton/scandalorian-scan-engine:amd64 \
          charlesdburton/scandalorian-scan-engine:arm \
          charlesdburton/scandalorian-scan-engine:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/scandalorian-scan-engine:${{ github.sha }} charlesdburton/scandalorian-scan-engine:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/scandalorian-scan-engine:${{ github.sha }} charlesdburton/scandalorian-scan-engine:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/scandalorian-scan-engine:${{ github.sha }} charlesdburton/scandalorian-scan-engine:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/scandalorian-scan-engine:${{ github.sha }}

  discovery-engine-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of discovery-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: discovery-engine
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-discovery-engine:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-discovery-engine:arm
  discovery-engine-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of discovery-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: discovery-engine
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-discovery-engine:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-discovery-engine:arm64
  discovery-engine-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of discovery-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: discovery-engine
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-discovery-engine:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-discovery-engine:amd64
  discovery-engine-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push discovery-engine
    needs: ["discovery-engine-build-arm", "discovery-engine-build-arm64", "discovery-engine-build-amd64"]
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/scandalorian-discovery-engine:${{ github.sha }} \
          charlesdburton/scandalorian-discovery-engine:amd64 \
          charlesdburton/scandalorian-discovery-engine:arm \
          charlesdburton/scandalorian-discovery-engine:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/scandalorian-discovery-engine:${{ github.sha }} charlesdburton/scandalorian-discovery-engine:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/scandalorian-discovery-engine:${{ github.sha }} charlesdburton/scandalorian-discovery-engine:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/scandalorian-discovery-engine:${{ github.sha }} charlesdburton/scandalorian-discovery-engine:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/scandalorian-discovery-engine:${{ github.sha }}      

  reversedns-engine-build-arm:
    runs-on: ubuntu-latest
    name: Build arm version of reversedns-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm
        working-directory: reversedns
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-reversedns-engine:arm --target=arm --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-reversedns-engine:arm
  reversedns-engine-build-arm64:
    runs-on: ubuntu-latest
    name: Build arm64 version of reversedns-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Arm64
        working-directory: reversedns
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-reversedns-engine:arm64 --target=arm64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-reversedns-engine:arm64
  reversedns-engine-build-amd64:
    runs-on: ubuntu-latest
    name: Build amd64 version of reversedns-engine
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build AMD64
        working-directory: reversedns
        run: DOCKER_BUILDKIT=1 docker build -t charlesdburton/scandalorian-reversedns-engine:amd64 --target=amd64 --file=./Dockerfile .
      - name: Push Image
        run: docker push charlesdburton/scandalorian-reversedns-engine:amd64
  reversedns-engine-build-manifest:
    runs-on: ubuntu-latest
    name: Collect manifest and push reversedns-engine
    needs: ["reversedns-engine-build-arm", "reversedns-engine-build-arm64", "reversedns-engine-build-amd64"]
    steps:
      - uses: actions/checkout@v2

      - name: Docker Login
        run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
      - name: Build Manifest
        run: |
          DOCKER_CLI_EXPERIMENTAL=enabled docker manifest create charlesdburton/scandalorian-reversedns-engine:${{ github.sha }} \
          charlesdburton/scandalorian-reversedns-engine:amd64 \
          charlesdburton/scandalorian-reversedns-engine:arm \
          charlesdburton/scandalorian-reversedns-engine:arm64 
      - name: Annotate Arm
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm charlesdburton/scandalorian-reversedns-engine:${{ github.sha }} charlesdburton/scandalorian-reversedns-engine:arm
      - name: Annotate Arm64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch arm64 charlesdburton/scandalorian-reversedns-engine:${{ github.sha }} charlesdburton/scandalorian-reversedns-engine:arm64
      - name: Annotate AMD64
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest annotate --arch amd64 charlesdburton/scandalorian-reversedns-engine:${{ github.sha }} charlesdburton/scandalorian-reversedns-engine:amd64
      - name: Push Manifest
        run: DOCKER_CLI_EXPERIMENTAL=enabled docker manifest push charlesdburton/scandalorian-reversedns-engine:${{ github.sha }}      

  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: ["discovery-engine-build-manifest","scan-engine-build-manifest","ingest-build-manifest", "reversedns-engine-build-manifest"]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "3.9.1"

      - name: Edit Kustomize
        run: |
          cd argocd
          kustomize edit set image charlesdburton/scandalorian-discovery-engine:latest=charlesdburton/scandalorian-discovery-engine:${{ github.sha }}
          kustomize edit set image charlesdburton/scandalorian-scan-engine:latest=charlesdburton/scandalorian-scan-engine:${{ github.sha }}
          kustomize edit set image charlesdburton/scandalorian-ingest:latest=charlesdburton/scandalorian-ingest:${{ github.sha }}
          cat kustomization.yaml

      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "Github Actions"
          git commit -a -m "Set Kustomization Docker Tag"
      
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.head_ref }}
